apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-configmap
  namespace: bookshop
data:
  application.yml: |
    server:
      port: ${SERVER_PORT:6001}

    security:
      jwt:
        public-key: classpath:jwt-signing-public-key.txt

    spring:
      profiles:
        active: ${SPRING_PROFILES_ACTIVE:mysql}
      zipkin:
        base-url: http://${ZIPKIN_HOST:localhost:9411}
        enabled: true
        service:
          name: bookstore-catalog-service
        message-timeout: 10
      sleuth:
        sampler:
          probability: 1.0
      flyway:
        table: catalog_service_flyway_history
        baseline-on-migrate: true
        baseline-version: 0.9
      main:
        allow-bean-definition-overriding: true
      hateoas:
        use-hal-as-default-json-media-type: false
      servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
      cloud:
        consul:
          enabled: false  

    logging:
      level:
        com.devd.spring.*: DEBUG

    ---

    spring:
      profiles: mysql
      jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: mysql
        open-in-view: true
        generate-ddl: true
        hibernate:
          ddl-auto: validate
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          hibernate:
            show_sql: true
            use_sql_comments: true
            format_sql: true
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql-service.bookshop.svc.cluster.local:3306/bookstore_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: bookstoreDBA
        password: PaSSworD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: bookshop
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: nguyenducc/catalog-service:v10
        ports:
        - containerPort: 6001
        volumeMounts:
        - name: catalog
          mountPath: "/app/src/main/resources/application.yml"
          subPath: application.yml
      volumes:
      - name: catalog  
        configMap:
          name: catalog-configmap
      # imagePullSecrets:
      # - name: harbor-secret    
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: bookshop
spec:
  selector:
    app: catalog
  ports:
  - port: 6001
    targetPort: 6001
  type: ClusterIP
