apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-frontend
  namespace: bookshop
spec:
  selector:
    matchLabels:
      app: bookshop-frontend
  template:
    metadata:
      labels:
        app: bookshop-frontend
    spec:
      containers:
      - name: bookshop-frontend
        image: nguyenducc/bookstore-frontend-microservice:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookshop-frontend-service
  namespace: bookshop
spec:
  selector:
    app: bookshop-frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookshop-frontend-ingress
  namespace: bookshop
spec:
  ingressClassName: nginx
  rules:
  - host: bookshop.ducnv.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: bookshop-frontend-service
            port: 
              number: 80
