apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-configmap
  namespace: bookshop
data:
  application.yml: |
    server:
      port: ${SERVER_PORT:8001}

    security:
      jwt:
        public-key: classpath:jwt-signing-public-key.txt

    service:
      stripeKey: sk_test_51HyGx6G9R9y827ntfKTizO243LzKHnaNIucO8i7apU0zuTIE5iNAes6l64aoWczGwiCnnBNsvvrgS95nfpbWa2cw00FnScmrhd

    spring:
      profiles:
        active: ${SPRING_PROFILES_ACTIVE:mysql}
      zipkin:
        base-url: http://${ZIPKIN_HOST:localhost:9411}
        enabled: true
        service:
          name: bookstore-payment-service
        message-timeout: 10
      sleuth:
        sampler:
          probability: 1.0
      flyway:
        table: payment_service_flyway_history
        baseline-on-migrate: true
        baseline-version: 0.9
      main:
        allow-bean-definition-overriding: true
      hateoas:
        use-hal-as-default-json-media-type: false
      cloud:
        consul:
          enabled: false 

    logging:
      level:
        com.devd.spring.*: DEBUG

    management:
      endpoint:
        hystrix:
          stream:
            enabled: true

    ---

    spring:
      profiles: mysql
      jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: mysql
        open-in-view: true
        generate-ddl: true
        hibernate:
          ddl-auto: validate
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          hibernate:
            show_sql: true
            use_sql_comments: true
            format_sql: true
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql-service.bookshop.svc.cluster.local:3306/bookstore_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: bookstoreDBA
        password: PaSSworD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: bookshop
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: nguyenducc/payment-service:v1
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: payment
          mountPath: "/app/src/main/resources/application.yml"
          subPath: application.yml
      volumes:
      - name: payment  
        configMap:
          name: payment-configmap
      # imagePullSecrets:
      # - name: harbor-secret    
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: bookshop
spec:
  selector:
    app: payment
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP  
